// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjkwtDuEf_i0GXhutyYyjv31KdUrkj_B0',
    appId: '1:138009320573:web:1eda1b184070b3ca8ce514',
    messagingSenderId: '138009320573',
    projectId: 'taskflow-app-3a43b',
    authDomain: 'taskflow-app-3a43b.firebaseapp.com',
    storageBucket: 'taskflow-app-3a43b.firebasestorage.app',
    measurementId: 'G-CE3V8FB1Q8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDy8Cx6VHMb3a6CXAIfxr0i93qu0kRuc3g',
    appId: '1:138009320573:android:3d795defd7f2d95c8ce514',
    messagingSenderId: '138009320573',
    projectId: 'taskflow-app-3a43b',
    storageBucket: 'taskflow-app-3a43b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLzTKT3TRduFgasEAjw_T0N0Y_kIvGD70',
    appId: '1:138009320573:ios:4bfb824a81342cc28ce514',
    messagingSenderId: '138009320573',
    projectId: 'taskflow-app-3a43b',
    storageBucket: 'taskflow-app-3a43b.firebasestorage.app',
    iosBundleId: 'com.example.taskFlow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLzTKT3TRduFgasEAjw_T0N0Y_kIvGD70',
    appId: '1:138009320573:ios:4bfb824a81342cc28ce514',
    messagingSenderId: '138009320573',
    projectId: 'taskflow-app-3a43b',
    storageBucket: 'taskflow-app-3a43b.firebasestorage.app',
    iosBundleId: 'com.example.taskFlow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjkwtDuEf_i0GXhutyYyjv31KdUrkj_B0',
    appId: '1:138009320573:web:f9a57806df588b358ce514',
    messagingSenderId: '138009320573',
    projectId: 'taskflow-app-3a43b',
    authDomain: 'taskflow-app-3a43b.firebaseapp.com',
    storageBucket: 'taskflow-app-3a43b.firebasestorage.app',
    measurementId: 'G-4TD426MB55',
  );
}
